# Generated by Django 5.0.6 on 2024-05-12 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='bookstore.books')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookstore.purchase')),
            ],
            options={
                'verbose_name_plural': 'Purchase Items',
            },
        ),
    ]
