# Generated by Django 5.0.6 on 2024-05-11 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('ISBN', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='bookstore.category')),
                ('publishing_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_company', to='bookstore.editorial')),
            ],
        ),
    ]
