# Generated by Django 5.0.6 on 2024-05-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(related_name='books_authors', to='bookstore.author'),
        ),
    ]
